//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Diff.
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Log.
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildCellBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Column Base Log.
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildColumnBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Row Base Log.
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildRowBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as CSV.
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as TSV.
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsTsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制整行到对面.
        /// </summary>
        public static string ContextMenu_CopyRowToAnother {
            get {
                return ResourceManager.GetString("ContextMenu_CopyRowToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制到对面.
        /// </summary>
        public static string ContextMenu_CopyToAnother {
            get {
                return ResourceManager.GetString("ContextMenu_CopyToAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract diff with this row as column header..
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑Reset Column Header.
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←Reset Row Header.
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部保存.
        /// </summary>
        public static string ContextMenu_SaveAll {
            get {
                return ResourceManager.GetString("ContextMenu_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ↑Set Column Header.
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ←Set Row Header.
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot;.
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return ResourceManager.GetString("DefaultLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;${ROW}&quot; was added..
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatAddedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;${ROW}&quot; was removed..
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatRemovedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${LEFT} → ${RIGHT}.
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultRowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return ResourceManager.GetString("GroupBox_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format.
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return ResourceManager.GetString("GroupBox_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Format.
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return ResourceManager.GetString("GroupBox_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Setting.
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return ResourceManager.GetString("GroupBox_ReadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string GroupBox_Style {
            get {
                return ResourceManager.GetString("GroupBox_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Color.
        /// </summary>
        public static string Label_AddedColor {
            get {
                return ResourceManager.GetString("Label_AddedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Row Log Format.
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_AddedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Rows({0}).
        /// </summary>
        public static string Label_AddedRows {
            get {
                return ResourceManager.GetString("Label_AddedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always expand cell diff.
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return ResourceManager.GetString("Label_AlwaysExpandCellDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Modified Row.
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return ResourceManager.GetString("Label_ColorModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Base Log Format.
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_ColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Header Color.
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return ResourceManager.GetString("Label_ColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Width.
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return ResourceManager.GetString("Label_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Cell Height.
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return ResourceManager.GetString("Label_FitRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus first diff when extracted.
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return ResourceManager.GetString("Label_FocusFirstDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore File Setting.
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return ResourceManager.GetString("Label_IgnoreFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Cell Log Format.
        /// </summary>
        public static string Label_LogFormat {
            get {
                return ResourceManager.GetString("Label_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Row Height.
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return ResourceManager.GetString("Label_MaxRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Row Height.
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return ResourceManager.GetString("Label_MinRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Cells({0}).
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return ResourceManager.GetString("Label_ModifiedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Color.
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return ResourceManager.GetString("Label_ModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Row Color.
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return ResourceManager.GetString("Label_ModifiedRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Rows({0}).
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return ResourceManager.GetString("Label_ModifiedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dialog if no diff.
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return ResourceManager.GetString("Label_NotifyEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Color.
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return ResourceManager.GetString("Label_RemovedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Row Log Format.
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_RemovedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Rows({0}).
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return ResourceManager.GetString("Label_RemovedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Base Log Format.
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_RowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Colors.
        /// </summary>
        public static string Label_RowColor {
            get {
                return ResourceManager.GetString("Label_RowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Color.
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return ResourceManager.GetString("Label_RowHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Height.
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return ResourceManager.GetString("Label_RowlHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first blank columns.
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip first blank rows.
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim last blank columns.
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim last blank rows.
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string MenuItem_Console {
            get {
                return ResourceManager.GetString("MenuItem_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MenuItem_Edit_Copy {
            get {
                return ResourceManager.GetString("MenuItem_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute external command.
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Commands.
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItem_File_Exit {
            get {
                return ResourceManager.GetString("MenuItem_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuItem_File_Save {
            get {
                return ResourceManager.GetString("MenuItem_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return ResourceManager.GetString("MenuItem_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setting.
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return ResourceManager.GetString("MenuItem_GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Left.
        /// </summary>
        public static string MenuItem_Merge_CopyToLeft {
            get {
                return ResourceManager.GetString("MenuItem_Merge_CopyToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Right.
        /// </summary>
        public static string MenuItem_Merge_CopyToRight {
            get {
                return ResourceManager.GetString("MenuItem_Merge_CopyToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Modified Cell.
        /// </summary>
        public static string MenuItem_Merge_NextModifiedCell {
            get {
                return ResourceManager.GetString("MenuItem_Merge_NextModifiedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Modified Column.
        /// </summary>
        public static string MenuItem_Merge_NextModifiedColumn {
            get {
                return ResourceManager.GetString("MenuItem_Merge_NextModifiedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Modified Row.
        /// </summary>
        public static string MenuItem_Merge_NextModifiedRow {
            get {
                return ResourceManager.GetString("MenuItem_Merge_NextModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Modified Cell.
        /// </summary>
        public static string MenuItem_Merge_PrevModifiedCell {
            get {
                return ResourceManager.GetString("MenuItem_Merge_PrevModifiedCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Modified Column.
        /// </summary>
        public static string MenuItem_Merge_PrevModifiedColumn {
            get {
                return ResourceManager.GetString("MenuItem_Merge_PrevModifiedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Modified Row.
        /// </summary>
        public static string MenuItem_Merge_PrevModifiedRow {
            get {
                return ResourceManager.GetString("MenuItem_Merge_PrevModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as Dst File.
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open as Src File.
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open dst File.
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open src file.
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Files.
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent File Sets.
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no difference..
        /// </summary>
        public static string Message_NoDiff {
            get {
                return ResourceManager.GetString("Message_NoDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart to apply the changes..
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting Diff ....
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return ResourceManager.GetString("Msg_ExtractingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;..
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return ResourceManager.GetString("Msg_OutofSheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Files ....
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return ResourceManager.GetString("Msg_ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not be displayed.
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return ResourceManager.GetString("Msg_Undisplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many records. Display only around diff..
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return ResourceManager.GetString("Msg_WarnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return ResourceManager.GetString("RadioButton_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Diff.
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return ResourceManager.GetString("RadioButton_ShowOnlyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Down.
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + I.
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + K.
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + L.
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Left.
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + O.
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Right.
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Up.
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return ResourceManager.GetString("Shortcut_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return ResourceManager.GetString("Shortcut_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit External Command.
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Commands.
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit File Setting.
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Settings.
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return ResourceManager.GetString("Title_GeneralSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst File Path.
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst Sheet.
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src File Path.
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src Sheet.
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap src and dst.
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Args.
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Word_Blank {
            get {
                return ResourceManager.GetString("Word_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaseSensitive.
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return ResourceManager.GetString("Word_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Header Index.
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return ResourceManager.GetString("Word_ColumnHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dst File.
        /// </summary>
        public static string Word_DstFile {
            get {
                return ResourceManager.GetString("Word_DstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExactMatch.
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return ResourceManager.GetString("Word_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Word_Font {
            get {
                return ResourceManager.GetString("Word_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Word_Japanese {
            get {
                return ResourceManager.GetString("Word_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launguage.
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Type.
        /// </summary>
        public static string Word_MatchType {
            get {
                return ResourceManager.GetString("Word_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Row Header Width.
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return ResourceManager.GetString("Word_MaxRowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Word_Merge {
            get {
                return ResourceManager.GetString("Word_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Word_Path {
            get {
                return ResourceManager.GetString("Word_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Word_Regex {
            get {
                return ResourceManager.GetString("Word_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Index.
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return ResourceManager.GetString("Word_RowHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Header Name.
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return ResourceManager.GetString("Word_RowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet.
        /// </summary>
        public static string Word_Sheet {
            get {
                return ResourceManager.GetString("Word_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Index.
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return ResourceManager.GetString("Word_SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string Word_SheetName {
            get {
                return ResourceManager.GetString("Word_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Src File.
        /// </summary>
        public static string Word_SrcFile {
            get {
                return ResourceManager.GetString("Word_SrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Startup Sheet.
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return ResourceManager.GetString("Word_StartupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
